// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdXMK6N3APD2h3KWO1BodEG9GG7TWVLuc',
    appId: '1:78687072872:web:ebae38e72497202ec041dd',
    messagingSenderId: '78687072872',
    projectId: 'tap-luyen-nghiem-tuc',
    authDomain: 'tap-luyen-nghiem-tuc.firebaseapp.com',
    storageBucket: 'tap-luyen-nghiem-tuc.firebasestorage.app',
    measurementId: 'G-WMZPYNE9HT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFR3dfcQAyTcD7ygK5L9K03nxOod7qOcc',
    appId: '1:78687072872:android:13d9a75fed0e15cec041dd',
    messagingSenderId: '78687072872',
    projectId: 'tap-luyen-nghiem-tuc',
    storageBucket: 'tap-luyen-nghiem-tuc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcfudbLVu3rgvjrecjBdHxVXwLy4jbIa4',
    appId: '1:78687072872:ios:5fc0932931b59c88c041dd',
    messagingSenderId: '78687072872',
    projectId: 'tap-luyen-nghiem-tuc',
    storageBucket: 'tap-luyen-nghiem-tuc.firebasestorage.app',
    iosClientId: '78687072872-ibmpltdtnd8qcsejrsbv935iv4davbj6.apps.googleusercontent.com',
    iosBundleId: 'com.example.tapluyen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcfudbLVu3rgvjrecjBdHxVXwLy4jbIa4',
    appId: '1:78687072872:ios:5fc0932931b59c88c041dd',
    messagingSenderId: '78687072872',
    projectId: 'tap-luyen-nghiem-tuc',
    storageBucket: 'tap-luyen-nghiem-tuc.firebasestorage.app',
    iosClientId: '78687072872-ibmpltdtnd8qcsejrsbv935iv4davbj6.apps.googleusercontent.com',
    iosBundleId: 'com.example.tapluyen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdXMK6N3APD2h3KWO1BodEG9GG7TWVLuc',
    appId: '1:78687072872:web:3464958dac635691c041dd',
    messagingSenderId: '78687072872',
    projectId: 'tap-luyen-nghiem-tuc',
    authDomain: 'tap-luyen-nghiem-tuc.firebaseapp.com',
    storageBucket: 'tap-luyen-nghiem-tuc.firebasestorage.app',
    measurementId: 'G-PPCBNH9FW3',
  );
}
